// portfolio.js

export const portfolio = [
  {
    year: "2025",
    projects: [
      {
        name: "Software Development",
        tags: "Development, Redesign, Architecture, Motion, Testing",
        img: "/images/work/work_007.png",
        bgColor: "#60312b",
        bannerImg: "/images/work/work_006.jpeg",
        bannerVideo: "/vids/vid1.mp4",
        client: "Sakura",
        title: "Sakura House",
        description: [
          "Sakura House is a Japanese fine-dining restaurant in New York, founded by chef Aiko Tanaka. The goal was to transform its culinary artistry into a modern digital experience with a scalable brand identity and strong online presence.",
          "We led the software development and system architecture, while also delivering motion-driven storytelling and digital redesign for their brand.",
          "Partnered with the founder, culinary team, and creative stakeholders to merge cultural authenticity with modern digital execution.",
        ],
        more: [
          "Built a modular, reusable component-based system for web and brand storytelling assets.",
          "Designed the system to scale across platforms (web, social, and in-house displays).",
          "Integrated cinematic storytelling into the brand's web and digital platforms.",
        ],
        images: [
          "/images/work/work_001.png",
          "/images/work/work_002.png",
          "/images/work/work_003.png",
          "/images/work/work_004.png",
          "/images/work/work_005.png",
          "/images/work/work_006.png",
          "/images/work/work_007.png",
        ],
        nextProject: "Easypack",
      },
      {
        name: "Mobile Development",
        tags: "Design, Mobile App, UX/UI, Motion",
        img: "/images/work/work_008.png",
        bgColor: "#101820",
        bannerImg: "/images/work/work_009.png",
        client: "Easypack",
        title: "Smart Car Parking App",
        description: [
          "Easypack Parking App is a smart car parking application designed to simplify urban mobility. Built with React Native and Expo for cross-platform performance, and powered by a Golang backend for efficiency, it helps drivers easily discover, reserve, and manage parking spots in real time.",
          "We led the end-to-end mobile development process, combining user-focused UX/UI design with motion-driven interactions to deliver a seamless parking experience.",
          "Collaborated with stakeholders to design a scalable system architecture that integrates modern mobile frameworks with robust backend services.",
        ],
        more: [
          "Developed a modular, reusable component system to accelerate app updates and feature rollouts.",
          "Implemented real-time parking availability and reservation management with optimized API handling.",
          "Designed motion-driven UI transitions for an intuitive and engaging user journey.",
        ],
        images: [
          "/images/work/work_010.png",
          "/images/work/work_011.png",
          "/images/work/work_012.png",
          "/images/work/work_013.png",
        ],
        nextProject: "Hidden Signal",
      },
      {
        name: "Hidden Signal",
        tags: "art direction, identity, web development",
        img: "/images/work/work_014.png",
        bgColor: "#151213",
        bannerImg: "/images/work/work_016.jpeg",
        bannerVideo: "/vids/vid2.mp4",
        client: "Experimental",
        description: [
          "Hidden Signal is a digital platform created for an architectural agency, designed to translate their bold, experimental vision into a modern online experience. Built with Next.js for performance, GSAP for smooth motion, and Cinema4D for 3D visualization, the site merges storytelling with architectural precision.",
          "We led the full-stack web development and creative execution, ensuring the platform delivered both aesthetic impact and technical scalability.",
          "Worked closely with the agency's design leads to craft a structured, motion-driven identity system that reflects their architectural philosophy.",
        ],
        more: [
          "Implemented immersive scroll-based animations and micro-interactions using GSAP for a fluid experience.",
          "Integrated 3D architectural models rendered in Cinema4D to showcase projects in an interactive format.",
          "Built a scalable, SEO-friendly Next.js architecture optimized for high performance and cross-device accessibility.",
        ],
        images: [
          "/images/work/work_015.png",
          "/images/work/work_018.jpeg",
          "/images/work/work_016.png",
          "/images/work/work_017.png",
        ],
        nextProject: "Hooke Optics",
      },
    ],
  },
  {
    year: "2024",
    projects: [
      {
        name: "Hooke Optics",
        tags: "Software, Algorithms, Motion",
        img: "/images/work/work_018.png",
        bgColor: "#163300",
        bannerImg: "/images/work/work_020.jpeg",
        client: "Hooke Optics",
        title: "Live Microscope Education Platform",
        description: [
          "Hooke Optics is an educational software platform that enables users to view live microscope feeds and share them in real time through integrated video calling. Built with Next.js, Prisma, and MongoDB, the platform brings scientific collaboration into the digital era.",
          "We led the software development and system architecture, focusing on seamless live streaming, collaboration tools, and a user-friendly interface for educators and students.",
          "Partnered with the client to merge high-performance backend systems with interactive frontend experiences, enabling scalable global classroom use.",
        ],
        more: [
          "Developed a robust real-time infrastructure to stream and share microscope feeds within collaborative video sessions.",
          "Built with Prisma and MongoDB to manage user data, sessions, and experiment archives efficiently.",
          "Designed an intuitive, accessible web interface optimized for both educators and students across devices.",
        ],
        images: [
          "/images/work/work_019.png",
          "/images/work/work_020.png",
          "/images/work/work_021.png",
          "/images/work/work_022.png",
        ],
        nextProject: "Mango Entertainment",
      },
      {
        name: "Mango Entertainment",
        tags: "frontend, backend, fullstack",
        img: "/images/work/work_023.png",
        bgColor: "#0F0C15",
        bannerImg: "/images/work/work_003.jpeg",
        client: "Publishing",
        description: [
          "Mango Entertainment is a live streaming platform designed to deliver films, music, and interactive experiences in one unified ecosystem. Built to engage users with high-quality streams and dynamic features, the platform bridges entertainment and technology seamlessly.",
          "We led the end-to-end development of the platform, focusing on scalable live video architecture, interactive engagement tools, and intuitive UX design.",
          "Partnered with entertainment producers and media teams to build a digital stage where creators can broadcast, connect, and monetize their content globally.",
        ],
        more: [
          "Engineered a robust live streaming infrastructure optimized for low latency and high-quality playback across devices.",
          "Integrated real-time features such as chat, gifting, and interactive overlays to boost audience engagement.",
          "Designed a modular and adaptive interface system, ensuring scalability for new content types and future media expansions.",
        ],
        images: [
          "/images/work/work_024.png",
          "/images/work/work_025.png",
          "/images/work/work_026.png",
        ],
        nextProject: "Prism Flow",
      },
    ],
  },
  {
    year: "2023",
    projects: [
      {
        name: "Nebula Grid",
        tags: "visual systems, branding",
        img: "/images/work/work_013.jpeg",
        bgColor: "#11131a",
        bannerImg: "/images/work/work_014.jpeg",
        client: "Agency Project",
        description: [
          "Nebula Grid is a modular branding system built on cosmic patterns and dynamic networks.",
          "It explores how structured grids can create endless visual variations while remaining recognizable.",
        ],
        more: [
          "The design process focused on creating a flexible system that could adapt to various media while maintaining a cohesive brand identity.",
          "Nebula Grid has been implemented in several high-profile campaigns and has received praise for its innovative approach to branding.",
        ],
        images: [
          "/images/work/work_015.jpeg",
          "/images/work/work_016.jpeg",
          "/images/work/work_017.jpeg",
        ],
        nextProject: "Flux Motion",
      },
      {
        name: "Flux Motion",
        tags: "motion, identity",
        img: "/images/work/work_018.jpeg",
        bgColor: "#141414",
        bannerImg: "/images/work/work_019.jpeg",
        client: "Tech Startup",
        description: [
          "Flux Motion combines fluid simulation with generative identity systems for fast-scaling brands.",
          "Its approach emphasizes adaptability across digital touchpoints.",
        ],
        more: [
          "Flux Motion was developed using advanced motion graphics techniques, focusing on creating a dynamic and adaptable brand identity that resonates across various platforms.",
          "The project has been recognized in the design community for its innovative use of motion in branding and has been featured in several industry publications.",
        ],
        images: ["/images/work/work_010.jpeg", "/images/work/work_020.jpeg"],
        nextProject: "Nebula Grid",
      },
    ],
  },
  {
    year: "2022",
    projects: [
      {
        name: "Lume",
        tags: "interactive, installation",
        img: "/images/work/work_020.jpeg",
        bgColor: "#1c1c1c",
        bannerImg: "/images/work/work_038.jpeg",
        client: "Art Festival",
        description: [
          "Lume is an interactive light-based installation that reacts to movement and sound.",
          "Its generative system creates evolving forms that encourage audience participation.",
        ],
        more: [
          "The installation was created using a combination of sensors, LED technology, and custom software to create an immersive experience that responds to the environment.",
          "Lume has been exhibited in several art festivals and has received acclaim for its innovative approach to interactive design.",
        ],
        images: ["/images/work/work_021.jpeg", "/images/work/work_022.jpeg"],
        nextProject: "Pulse Identity",
      },
      {
        name: "Pulse Identity",
        tags: "brand, motion",
        img: "/images/work/work_023.jpeg",
        bgColor: "#0d0d0d",
        bannerImg: "/images/work/work_024.jpeg",
        client: "Music Label",
        description: [
          "Pulse Identity visualizes rhythm and frequency through dynamic identity motion systems.",
          "The brand expands and contracts in sync with audio waves.",
        ],
        more: [
          "The project involved close collaboration with sound designers to create a visual identity that truly embodies the essence of music and rhythm.",
          "Pulse Identity has been featured in various design and music industry publications for its innovative approach to brand motion.",
        ],
        images: ["/images/work/work_007.jpeg", "/images/work/work_008.jpeg"],
        nextProject: "Lume",
      },
    ],
  },
  {
    year: "2021",
    projects: [
      {
        name: "Fragment",
        tags: "experimental, design",
        img: "/images/work/work_009.jpeg",
        bgColor: "#121212",
        bannerImg: "/images/work/work_010.jpeg",
        client: "Personal",
        description: [
          "Fragment is an experimental exploration of broken forms and glitch aesthetics.",
          "It examines the beauty of distortion and decay in modern visuals.",
        ],
        more: [
          "The project was created using a mix of digital and analog techniques, including data bending and circuit manipulation, to achieve its unique aesthetic.",
          "Fragment has been showcased in several design exhibitions and has received recognition for its innovative approach to visual experimentation.",
        ],
        images: ["/images/work/work_011.jpeg", "/images/work/work_012.jpeg"],
        nextProject: "Waveform",
      },
      {
        name: "Waveform",
        tags: "motion, music",
        img: "/images/work/work_013.jpeg",
        bgColor: "#181a1f",
        bannerImg: "/images/work/work_014.jpeg",
        client: "Audio Collective",
        description: [
          "Waveform is a motion project translating audio data into dynamic shapes.",
          "It creates a bridge between sound design and visual design.",
        ],
        more: [
          "The project utilized advanced audio analysis tools to convert sound frequencies into visual elements, resulting in a captivating representation of music through motion.",
          "Waveform has been featured in several multimedia art shows and has been praised for its innovative fusion of audio and visual design.",
        ],
        images: ["/images/work/work_015.jpeg", "/images/work/work_016.jpeg"],
        nextProject: "Fragment",
      },
    ],
  },
  {
    year: "2020",
    projects: [
      {
        name: "Solaris",
        tags: "3D, identity",
        img: "/images/work/work_017.jpeg",
        bgColor: "#0e0e0e",
        bannerImg: "/images/work/work_018.jpeg",
        client: "Innovation Lab",
        description: [
          "Solaris is a 3D brand identity inspired by planetary motion and cosmic energy.",
          "Its animated identity system revolves endlessly to simulate orbital mechanics.",
        ],
        more: [
          "The project was developed using cutting-edge 3D modeling and animation software, focusing on creating a visually striking and conceptually rich brand identity.",
          "Solaris has been recognized in the design community for its innovative approach to brand identity and has been featured in several industry publications.",
        ],
        images: ["/images/work/work_019.jpeg", "/images/work/work_020.jpeg"],
        nextProject: "Kinetic Type",
      },
      {
        name: "Kinetic Type",
        tags: "typography, experimental",
        img: "/images/work/work_021.jpeg",
        bgColor: "#1a1a1a",
        bannerImg: "/images/work/work_022.jpeg",
        client: "University Project",
        description: [
          "Kinetic Type is a typography experiment focusing on rhythm, pace, and energy.",
          "It seeks to transform language into a living, breathing system.",
        ],
        more: [
          "The project involved extensive exploration of typographic forms and their potential for motion, resulting in a typeface that adapts fluidly to various contexts.",
          "Kinetic Type has been showcased in several design exhibitions and has received accolades for its innovative approach to typography.",
        ],
        images: ["/images/work/work_023.jpeg", "/images/work/work_025.jpeg"],
        nextProject: "Solaris",
      },
    ],
  },
  {
    year: "2019",
    projects: [
      {
        name: "Origin",
        tags: "branding, visual identity",
        img: "/images/work/work_024.jpeg",
        bgColor: "#191919",
        bannerImg: "/images/work/work_025.jpeg",
        client: "First Client Project",
        description: [
          "Origin was an early branding project exploring simplicity and timeless forms.",
          "It laid the foundation for an adaptable visual system.",
        ],
        more: [
          "The project focused on creating a clean and versatile brand identity that could be easily adapted across various media and platforms.",
          "Origin has been used as a case study in branding courses and has been praised for its effective use of minimalism in design.",
        ],
        images: ["/images/work/work_001.jpeg", "/images/work/work_002.jpeg"],
        nextProject: "Momentum",
      },
      {
        name: "Momentum",
        tags: "motion, experimental",
        img: "/images/work/work_003.jpeg",
        bgColor: "#111111",
        bannerImg: "/images/work/work_006.jpeg",
        client: "Exploration",
        description: [
          "Momentum was my first motion-focused piece, testing ideas around velocity and time.",
          "It represents the start of my exploration into motion systems.",
        ],
        more: [
          "The project was created using basic animation techniques to explore the concepts of speed and movement, laying the groundwork for more complex motion design work in the future.",
          "Momentum has been featured in several student showcases and has received positive feedback for its innovative approach to motion design.",
        ],
        images: ["/images/work/work_007.jpeg", "/images/work/work_008.jpeg"],
        nextProject: "Origin",
      },
    ],
  },
];
