// portfolio.js

export const portfolio = [
  {
    year: "2025",
    projects: [
      {
        name: "Echo",
        tags: "creative direction, design",
        img: "/images/work/work_007.jpeg",
        bgColor: "#0d1117",
        bannerImg: "/images/work/work_006.jpeg",
        client: "Self-Initiated",
        description: [
          "Echo is an exploration of motion through layered temporal loops. Built with a modular design system, the visuals pulse and stretch to reflect the elasticity of time in digital environments.",
          "The concept embraces minimal forms with high contrast dynamics to suggest an ongoing shift — folding the present into an abstract continuum.",
        ],
        images: [
          "/images/work/work_001.jpeg",
          "/images/work/work_021.jpeg",
          "/images/work/work_003.jpeg",
          "/images/work/work_009.jpeg",
          "/images/work/work_015.jpeg",
          "/images/work/work_023.jpeg",
          "/images/work/work_024.jpeg",
        ],
        nextProject: "Nocturne Blur",
      },
      {
        name: "Nocturne Blur",
        tags: "motion, design",
        img: "/images/work/work_002.jpeg",
        bgColor: "#101820",
        bannerImg: "/images/work/work_010.jpeg",
        client: "Studio Collab",
        description: [
          "Nocturne Blur captures the fluidity of night through abstract compositions and animated gradients.",
          "Its identity plays with depth, opacity, and rhythm to blur the line between static and motion-driven design.",
        ],
        images: [
          "/images/work/work_012.jpeg",
          "/images/work/work_013.jpeg",
          "/images/work/work_014.jpeg",
          "/images/work/work_015.jpeg",
        ],
        nextProject: "Hidden Signal",
      },
      {
        name: "Hidden Signal",
        tags: "art direction, identity",
        img: "/images/work/work_003.jpeg",
        bgColor: "#181818",
        bannerImg: "/images/work/work_016.jpeg",
        client: "Experimental",
        description: [
          "Hidden Signal is a conceptual identity system inspired by encrypted messages and fragmented communication.",
          "Its visual language leverages distortion, grids, and overlays to build a mysterious yet structured brand story.",
        ],
        images: [
          "/images/work/work_017.jpeg",
          "/images/work/work_018.jpeg",
          "/images/work/work_019.jpeg",
        ],
        nextProject: "Echo",
      },
    ],
  },
  {
    year: "2024",
    projects: [
      {
        name: "Prism Flow",
        tags: "3D, animation",
        img: "/images/work/work_004.jpeg",
        bgColor: "#1a1f2b",
        bannerImg: "/images/work/work_020.jpeg",
        client: "Freelance",
        description: [
          "Prism Flow explores color as liquid geometry — shapes bend and refract light to simulate organic prisms.",
          "The work experiments with generative visuals and adaptive gradients for brand storytelling.",
        ],
        images: [
          "/images/work/work_021.jpeg",
          "/images/work/work_022.jpeg",
          "/images/work/work_023.jpeg",
        ],
        nextProject: "Monarch Type",
      },
      {
        name: "Monarch Type",
        tags: "typography, motion",
        img: "/images/work/work_005.jpeg",
        bgColor: "#0f0f0f",
        bannerImg: "/images/work/work_024.jpeg",
        client: "Publishing",
        description: [
          "Monarch Type is a kinetic typography experiment that balances symmetry and chaos.",
          "Through dynamic animations, it pushes type design into a responsive storytelling framework.",
        ],
        images: [
          "/images/work/work_025.jpeg",
          "/images/work/work_026.jpeg",
          "/images/work/work_027.jpeg",
        ],
        nextProject: "Prism Flow",
      },
    ],
  },
  {
    year: "2023",
    projects: [
      {
        name: "Nebula Grid",
        tags: "visual systems, branding",
        img: "/images/work/work_013.jpeg",
        bgColor: "#11131a",
        bannerImg: "/images/work/work_014.jpeg",
        client: "Agency Project",
        description: [
          "Nebula Grid is a modular branding system built on cosmic patterns and dynamic networks.",
          "It explores how structured grids can create endless visual variations while remaining recognizable.",
        ],
        images: [
          "/images/work/work_015.jpeg",
          "/images/work/work_016.jpeg",
          "/images/work/work_017.jpeg",
        ],
        nextProject: "Flux Motion",
      },
      {
        name: "Flux Motion",
        tags: "motion, identity",
        img: "/images/work/work_018.jpeg",
        bgColor: "#141414",
        bannerImg: "/images/work/work_019.jpeg",
        client: "Tech Startup",
        description: [
          "Flux Motion combines fluid simulation with generative identity systems for fast-scaling brands.",
          "Its approach emphasizes adaptability across digital touchpoints.",
        ],
        images: ["/images/work/work_010.jpeg", "/images/work/work_020.jpeg"],
        nextProject: "Nebula Grid",
      },
    ],
  },
  {
    year: "2022",
    projects: [
      {
        name: "Lume",
        tags: "interactive, installation",
        img: "/images/work/work_020.jpeg",
        bgColor: "#1c1c1c",
        bannerImg: "/images/work/work_038.jpeg",
        client: "Art Festival",
        description: [
          "Lume is an interactive light-based installation that reacts to movement and sound.",
          "Its generative system creates evolving forms that encourage audience participation.",
        ],
        images: ["/images/work/work_021.jpeg", "/images/work/work_022.jpeg"],
        nextProject: "Pulse Identity",
      },
      {
        name: "Pulse Identity",
        tags: "brand, motion",
        img: "/images/work/work_023.jpeg",
        bgColor: "#0d0d0d",
        bannerImg: "/images/work/work_024.jpeg",
        client: "Music Label",
        description: [
          "Pulse Identity visualizes rhythm and frequency through dynamic identity motion systems.",
          "The brand expands and contracts in sync with audio waves.",
        ],
        images: ["/images/work/work_007.jpeg", "/images/work/work_008.jpeg"],
        nextProject: "Lume",
      },
    ],
  },
  {
    year: "2021",
    projects: [
      {
        name: "Fragment",
        tags: "experimental, design",
        img: "/images/work/work_009.jpeg",
        bgColor: "#121212",
        bannerImg: "/images/work/work_010.jpeg",
        client: "Personal",
        description: [
          "Fragment is an experimental exploration of broken forms and glitch aesthetics.",
          "It examines the beauty of distortion and decay in modern visuals.",
        ],
        images: ["/images/work/work_011.jpeg", "/images/work/work_012.jpeg"],
        nextProject: "Waveform",
      },
      {
        name: "Waveform",
        tags: "motion, music",
        img: "/images/work/work_013.jpeg",
        bgColor: "#181a1f",
        bannerImg: "/images/work/work_014.jpeg",
        client: "Audio Collective",
        description: [
          "Waveform is a motion project translating audio data into dynamic shapes.",
          "It creates a bridge between sound design and visual design.",
        ],
        images: ["/images/work/work_015.jpeg", "/images/work/work_016.jpeg"],
        nextProject: "Fragment",
      },
    ],
  },
  {
    year: "2020",
    projects: [
      {
        name: "Solaris",
        tags: "3D, identity",
        img: "/images/work/work_017.jpeg",
        bgColor: "#0e0e0e",
        bannerImg: "/images/work/work_018.jpeg",
        client: "Innovation Lab",
        description: [
          "Solaris is a 3D brand identity inspired by planetary motion and cosmic energy.",
          "Its animated identity system revolves endlessly to simulate orbital mechanics.",
        ],
        images: ["/images/work/work_019.jpeg", "/images/work/work_020.jpeg"],
        nextProject: "Kinetic Type",
      },
      {
        name: "Kinetic Type",
        tags: "typography, experimental",
        img: "/images/work/work_021.jpeg",
        bgColor: "#1a1a1a",
        bannerImg: "/images/work/work_022.jpeg",
        client: "University Project",
        description: [
          "Kinetic Type is a typography experiment focusing on rhythm, pace, and energy.",
          "It seeks to transform language into a living, breathing system.",
        ],
        images: ["/images/work/work_023.jpeg", "/images/work/work_025.jpeg"],
        nextProject: "Solaris",
      },
    ],
  },
  {
    year: "2019",
    projects: [
      {
        name: "Origin",
        tags: "branding, visual identity",
        img: "/images/work/work_024.jpeg",
        bgColor: "#191919",
        bannerImg: "/images/work/work_025.jpeg",
        client: "First Client Project",
        description: [
          "Origin was an early branding project exploring simplicity and timeless forms.",
          "It laid the foundation for an adaptable visual system.",
        ],
        images: ["/images/work/work_001.jpeg", "/images/work/work_002.jpeg"],
        nextProject: "Momentum",
      },
      {
        name: "Momentum",
        tags: "motion, experimental",
        img: "/images/work/work_003.jpeg",
        bgColor: "#111111",
        bannerImg: "/images/work/work_006.jpeg",
        client: "Exploration",
        description: [
          "Momentum was my first motion-focused piece, testing ideas around velocity and time.",
          "It represents the start of my exploration into motion systems.",
        ],
        images: ["/images/work/work_007.jpeg", "/images/work/work_008.jpeg"],
        nextProject: "Origin",
      },
    ],
  },
];
